[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "farm_schema"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"

# Only list dependencies your app actually needs
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.13.3",
    "python-dotenv>=1.2.1"
]

[project.scripts]
my-app = "my_app.main:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]